# Generated by Django 4.2 on 2023-04-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_engineering_discipline_profile_year_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='engineering_discipline',
            field=models.CharField(blank=True, choices=[('data', 'Data'), ('electronics', 'Electronics'), ('electrical', 'Electrical')], max_length=12),
        ),
    ]
