# Generated by Django 4.2 on 2023-04-14 08:53

import django.core.validators
from django.db import migrations, models 


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_engineering_discipline'),
    ]

    def set_student_year_default(apps, schema_editor):
        Profile = apps.get_model('users', 'Profile')
        Profile.objects.update(student_year='1')

    operations = [

        migrations.AddField(
            model_name='profile',
            name='desired_grade',
            field=models.CharField(choices=[('p', 'P'), ('c', 'C'), ('d', 'D'), ('hd', 'HD')], default='P', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='on_campus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='student_id_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='student_last_name',
            field=models.CharField(default='Dent', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='student_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='studio_level',
            field=models.CharField(blank=True, choices=[('fundamentals a', 'Fundamentals A'), ('fundamentals b', 'Fundamentals B'), ('applications a', 'Applications A'), ('applications b', 'Applications B'), ('professionals a', 'Professionals A'), ('professionals b', 'Professionals B')], max_length=20),
        ),
    ]
