# Generated by Django 4.2 on 2023-04-14 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_year_level_profile_desired_grade_and_more'),
    ]

    operations = [    ]
