# Generated by Django 4.2 on 2023-04-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_student_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='year_level',
        ),
        migrations.AddField(
            model_name='profile',
            name='student_first_name',
            field=models.CharField(default='Stu', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_year',
            field=models.IntegerField(default=1),
        ),
    ]
