# Generated by Django 3.2.18 on 2023-04-19 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_id_number'),
        ('preferences', '0003_auto_20230416_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='p1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_pref', to='products.product'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='p2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_pref', to='products.product'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='p3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_pref', to='products.product'),
        ),
    ]
