# Generated by Django 4.2 on 2023-04-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_number', models.IntegerField(default=94)),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=255)),
                ('skills', models.TextField(blank=True)),
            ],
        ),
    ]
