# Generated by Django 3.2.18 on 2023-04-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_number',
            field=models.IntegerField(default=73),
        ),
    ]
